rdma_cm: add lib/rdma_cm to wrap up rdma cm operations
lib/rdma_cm is used as an abstract layer to wrap up RDMA connection
establishment primitives. With this abstract layer, users can customize
RDMA connection establishment workflows with special optimizations, such
as dynamic RNIC selection, non-standard parameters, etc..

This patch introduces the interface of lib/rdma_cm, which covers all
librdmacm APIs currently used in SPDK, and two implementations of the
interface:

rdma_cm_cma.c: thin wrapper of librdmacm, simply forward all lib/rdma_cm
function calls to their librdmacm counterparts.

rdma_cm_mock.c: a dummy implementation for tests.

This patch also adds a configuration option --with-rdma-cm=CM for
specifying the lib/rdma_cm implementation to use. The default value is
"cma", which means using the librdmacm thin wrapper.

No functional change should be introduced for now.

Change-Id: I5b9bbce32c8a1277419517b68601d79a519a0f5f
Signed-off-by: Jinlong Chen <chenjinlong.cjl@alibaba-inc.com>
Reviewed-on: https://review.spdk.io/c/spdk/spdk/+/28394
Community-CI: Mellanox Build Bot
Reviewed-by: Aleksey Marchuk <alexeymar@nvidia.com>
Tested-by: SPDK Automated Test System <spdkbot@gmail.com>
Reviewed-by: Jim Harris <jim.harris@nvidia.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -88,6 +88,8 @@ function usage() {
 	echo " --with-rdma[=PROVIDER]    Build RDMA transport for NVMf target and initiator."
 	echo " --without-rdma            Accepts optional RDMA provider name. Can be \"verbs\" or \"mlx5_dv\"."
 	echo "                           If no provider specified, \"verbs\" provider is used by default."
+	echo " --with-rdma-cm=CM         Use a custom connection manager library for RDMA transport."
+	echo "                           If not specified, librdmacm (cma) will be used."
 	echo " --with-fc[=DIR]           Build FC transport for NVMf target."
 	echo " --without-fc              If an argument is provided, it is considered a directory containing"
 	echo "                           libufc.a and fc_lld.h. Otherwise the regular system paths will"
@@ -482,6 +484,9 @@ for i in "$@"; do
 			;;
 		--without-rdma)
 			CONFIG[RDMA]=n
+			;;
+		--with-rdma-cm=*)
+			CONFIG[RDMA_CM]="${i#*=}"
 			;;
 		--with-fc=*)
 			CONFIG[FC]=y
@@ -966,6 +971,13 @@ than or equal to 4.14 will see significantly reduced performance.
 	fi
 
 	echo "Using '${CONFIG[RDMA_PROV]}' RDMA provider"
+
+	if [[ ! "${CONFIG[RDMA_CM]}" == "cma" ]] && [[ ! "${CONFIG[RDMA_CM]}" == "mock" ]]; then
+		echo "Invalid RDMA connection manager specified, must be \"cma\" or \"mock\""
+		exit 1
+	fi
+
+	echo "Using '${CONFIG[RDMA_CM]}' RDMA connection manager"
 fi
 
 if [[ "${CONFIG[FC]}" = "y" ]]; then
