doc: update root README.md
First in a series of doc updates. This removes some duplicate info
that we also have on spdk.io and replaces some of the links found
on that site with a link to spdk.io. Also fixes a few minor missing
steps for all OSs and all were tested from a fresh install
by copying and pasting only info from the readme.

Upcoming patches include removing duplicate info from the developer
section of spdk.io and expanding this readme to include simple
walkthroughs for patch creation & submission. The intent is that
the quick and easy steps are documented here and the supporting
information and more complex operations be covered on spdk.io in
the developer tab.

Slight changes made to /configure to be more FreeBSD friendly and
match the readme.

Change-Id: Ibbe5a070488cf295c1decd1a8b72b23fd140e942
Signed-off-by: Paul Luse <paul.e.luse@intel.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -150,6 +150,14 @@ if [ "$CONFIG_ASAN" = "y" -a "$CONFIG_TSAN" = "y" ]; then
 	exit 1
 fi
 
+if [[ "$OSTYPE" == "FreeBSD"* ]]; then
+	# FreeBSD doesn't support all configurations
+	if [[ "$CONFIG_COVERAGE" == "y" ]]; then
+		echo "ERROR: CONFIG_COVERAGE not available on FreeBSD"
+		exit 1
+	fi
+fi
+
 echo -n "Creating CONFIG.local..."
 
 # Write the configuration file
@@ -197,6 +205,10 @@ fi
 python scripts/genconfig.py > config.h
 
 echo "done."
-echo "Type 'make' to build."
+if [[ "$OSTYPE" == "FreeBSD"* ]]; then
+        echo "Type 'gmake' to build."
+else
+        echo "Type 'make' to build."
+fi
 
 exit 0
