build: Conditionally builds single and separate shared libs
Adds option to configure script (default is disabled)
to build SPDK shared libraries, and enhances build
correspondingly to do so.  This includes the single, combined
shared library encompassing all of the SPDK static libs,
as well as production of individual SPDK shared libraries
corresponding to each of the static ones.  Although the
SPDK shared libs conform with shared lib naming conventions
complete with version numbering suffixes, this does not
confer any ABI compatibility claims whatsoever at this time.
It's merely conformance with the naming conventions.
Finally, there are no built-in dependencies between SPDK
shared libs, thus requiring one to specify all needed SPDK
shared libs to resolve all symbols in the final link of an
executable wishing to use said SPDK shared libs.

Change-Id: Ia375c0e3fb6d150d45a39e84e3b226fbaea48545
Signed-off-by: Lance Hartmann <lance.hartmann@oracle.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -51,6 +51,8 @@ function usage()
 	echo "                           No path required."
 	echo " rdma                      [disabled]"
 	echo "                           No path required."
+	echo " shared                    Required to build spdk shared libraries."
+	echo "                           No path required."
 	echo " iscsi-initiator           [disabled]"
 	echo "                           No path required."
 	echo " raid                      [disabled]"
@@ -157,6 +159,12 @@ for i in "$@"; do
 			;;
 		--without-rdma)
 			CONFIG_RDMA=n
+			;;
+		--with-shared)
+			CONFIG_SHARED=y
+			;;
+		--without-shared)
+			CONFIG_SHARED=n
 			;;
 		--with-iscsi-initiator)
 			CONFIG_ISCSI_INITIATOR=y
@@ -291,10 +299,14 @@ if [ "$CONFIG_ASAN" = "y" -a "$CONFIG_TSAN" = "y" ]; then
 	exit 1
 fi
 
-if [[ "$OSTYPE" == "FreeBSD"* ]]; then
+if [[ "${OSTYPE,freebsd}" == "freebsd"* ]]; then
 	# FreeBSD doesn't support all configurations
 	if [[ "$CONFIG_COVERAGE" == "y" ]]; then
 		echo "ERROR: CONFIG_COVERAGE not available on FreeBSD"
+		exit 1
+	fi
+	if [[ "$CONFIG_SHARED" == "y" ]]; then
+		echo "ERROR: CONFIG_SHARED not available on FreeBSD"
 		exit 1
 	fi
 fi
@@ -369,6 +381,9 @@ fi
 if [ -n "$CONFIG_RDMA" ]; then
 	echo "CONFIG_RDMA?=$CONFIG_RDMA" >> CONFIG.local
 fi
+if [ -n "$CONFIG_SHARED" ]; then
+	echo "CONFIG_SHARED?=$CONFIG_SHARED" >> CONFIG.local
+fi
 if [ -n "$CONFIG_ISCSI_INITIATOR" ]; then
 	echo "CONFIG_ISCSI_INITIATOR?=$CONFIG_ISCSI_INITIATOR" >> CONFIG.local
 fi
@@ -415,7 +430,7 @@ echo $python_command > PYTHON_COMMAND
 $python_command scripts/genconfig.py > config.h
 
 echo "done."
-if [[ "$OSTYPE" == "FreeBSD"* ]]; then
+if [[ "${OSTYPE,freebsd}" == "freebsd"* ]]; then
 	echo "Type 'gmake' to build."
 else
 	echo "Type 'make' to build."
