NVMe-oF Target: Add FC transport.
  - New files and updates to existing SPDK files to add the NVMf-FC transport.
  - Depends on an existing low level driver library. This driver is not part of SPDK repository.
  - Makefile updates to build FC transport (using CONFIG_FC)
  - Update configure script for FC build.
  - New FC unit test for FC-LS commands.
  - Update unittest.sh to run FC unit test (when built).

Signed-off-by: John Barnard <john.barnard@broadcom.com>
Signed-off-by: Anil Veerabhadrappa <anil.veerabhadrappa@broadcom.com>
Change-Id: If31d4d25feab76c2dbe90a7faf71d465c2c3a354

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -66,6 +66,10 @@ function usage()
 	echo "                           No path required."
 	echo " rdma                      Build RDMA transport for NVMf target and initiator."
 	echo "                           No path required."
+	echo " fc                        Build FC transport for NVMf target."
+	echo "                           If an argument is provided, it is considered a directory containing"
+	echo "                           libufc.a and fc_lld.h. Otherwise the regular system paths will"
+	echo "                           be searched."
 	echo " shared                    Build spdk shared libraries."
 	echo "                           No path required."
 	echo " iscsi-initiator           Build with iscsi bdev module."
@@ -210,6 +214,18 @@ for i in "$@"; do
 			;;
 		--without-rdma)
 			CONFIG[RDMA]=n
+			;;
+		--with-fc=*)
+			CONFIG[FC]=y
+			CONFIG[FC_PATH]=$(readlink -f ${i#*=})
+			;;
+		--with-fc)
+			CONFIG[FC]=y
+			CONFIG[FC_PATH]=
+			;;
+		--without-fc)
+			CONFIG[FC]=n
+			CONFIG[FC_PATH]=
 			;;
 		--with-shared)
 			CONFIG[SHARED]=y
@@ -479,6 +495,15 @@ be unable to leverage that operation using the currently installed version
 of libibverbs, so Linux kernel NVMe-oF initiators based on kernels greater
 than or equal to 4.14 will see significantly reduced performance.
 *******************************************************************************"
+	fi
+fi
+
+if [[ "${CONFIG[FC]}" = "y" ]]; then
+	if [[ -n "${CONFIG[FC_PATH]}" ]]; then
+		if [ ! -d "${CONFIG[FC_PATH]}" ]; then
+			echo "${CONFIG[FC_PATH]}: directory not found"
+			exit 1
+		fi
 	fi
 fi
 
