make: build custom dpdk
Build custom DPDK_DIR the same way as we do it with our submodule.
This will simplify testing with DPDK master or custom DPDK versions.

Note:
- in configure, don't need to check if DPDK_DIR exists
  because it can be empty now (in which case we will create it).
- in configure, we usually checked if rte_vhost version is
  supported by compiling a test file with it. Now it will not work if
  rte_vhost not built yet, so just print a message.
- clean will remove DPDK_DIR unconditionally.
  This can be improved if we remember who built it.

Change-Id: I1a7212067500d265662724f2392712890c987eea
Signed-off-by: Vitaliy Mysak <vitaliy.mysak@intel.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -210,7 +210,6 @@ for i in "$@"; do
 			CONFIG[WERROR]=n
 			;;
 		--with-dpdk=*)
-			check_dir "$i"
 			CONFIG[DPDK_DIR]=$(readlink -f ${i#*=})
 			;;
 		--without-dpdk)
@@ -437,16 +436,21 @@ if [ -z "${CONFIG[ENV]}" ]; then
 		fi
 	else
 		if [[ "${CONFIG[VHOST]}" = "y" ]] && [[ "${CONFIG[VHOST_INTERNAL_LIB]}" = "n" ]]; then
-			# DPDK must be already built, so we can simply try to use the new rte_vhost.
-			# It has a number of internal dependencies though, so don't try to link the
-			# program, just compile it
-			if ! echo -e '#include <rte_vhost.h>\n' \
-				'int main(void) { return rte_vhost_extern_callback_register(0, NULL, NULL); }\n' \
-				| ${BUILD_CMD[@]} -c -Wno-deprecated-declarations -Werror \
-				-I"${CONFIG[DPDK_DIR]}/include" - &>/dev/null; then
-				echo "Notice: DPDK's rte_vhost not found or version < 19.05, using internal," \
-				     "legacy rte_vhost library."
-				CONFIG[VHOST_INTERNAL_LIB]=y
+			if [ -d "${CONFIG[DPDK_DIR]}" ]; then
+				# DPDK must be already built, so we can simply try to use the new rte_vhost.
+				# It has a number of internal dependencies though, so don't try to link the
+				# program, just compile it
+				if ! echo -e '#include <rte_vhost.h>\n' \
+					'int main(void) { return rte_vhost_extern_callback_register(0, NULL, NULL); }\n' \
+					| ${BUILD_CMD[@]} -c -Wno-deprecated-declarations -Werror \
+					-I"${CONFIG[DPDK_DIR]}/include" - &>/dev/null; then
+					echo "Notice: DPDK's rte_vhost not found or version < 19.05, using internal," \
+					     "legacy rte_vhost library."
+					CONFIG[VHOST_INTERNAL_LIB]=y
+				fi
+			else
+				echo "Please make sure that rte_vhost is at least version 19.05"
+				echo "Otherwise --with-internal-vhost-lib should be used"
 			fi
 		fi
 	fi
