configure: handle the assignment of arbitrary DPDK DIR path
Change-Id: I13e270cb12c8f2796928c72338e50d30b5c8b08e
Signed-off-by: GangCao <gang.cao@intel.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -47,6 +47,15 @@ function usage()
 	echo ""
 }
 
+function check_dir() {
+	arg="$1"
+	dir="${arg#*=}"
+	if [ ! -d "$dir" ]; then
+		echo "$arg: directory not found"
+		exit 1
+	fi
+}
+
 for i in "$@"; do
 	case "$i" in
 		-h|--help)
@@ -114,6 +123,7 @@ for i in "$@"; do
 			CONFIG_RDMA=n
 			;;
 		--with-dpdk=*)
+			check_dir "$i"
 			CONFIG_DPDK_DIR=$(readlink -f ${i#*=})
 			;;
 		--without-dpdk)
