accel/dpdk_cryptodev: Support uadk crypto pmd
Add support of UADK Crypto Poll Mode Driver to accel/dpdk_cryptodev.

Build:
./configure --with-dpdk-uadk --with-crypto
make

Run
./build/bin/spdk_tgt -m 0xf0 --wait-for-rpc

./scripts/rpc.py dpdk_cryptodev_scan_accel_module
./scripts/rpc.py dpdk_cryptodev_set_driver -d crypto_uadk
./scripts/rpc.py accel_assign_opc -o encrypt -m dpdk_cryptodev
./scripts/rpc.py accel_assign_opc -o decrypt -m dpdk_cryptodev
./scripts/rpc.py framework_start_init

Change-Id: I73b763bdcf16c172501a3c2e785450401e8d54b2
Signed-off-by: Zhangfei Gao <zhangfei.gao@linaro.org>
Reviewed-on: https://review.spdk.io/gerrit/c/spdk/spdk/+/22979
Community-CI: Mellanox Build Bot
Reviewed-by: Jim Harris <jim.harris@samsung.com>
Tested-by: SPDK CI Jenkins <sys_sgci@intel.com>
Reviewed-by: Marcin Spiewak <marcin.spiewak@intel.com>
Reviewed-by: Aleksey Marchuk <alexeymar@nvidia.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -107,6 +107,8 @@ function usage() {
 	echo " --without-uring           If an argument is provided, it is considered a directory containing"
 	echo "                           liburing.a and io_uring.h. Otherwise the regular system paths will"
 	echo "                           be searched."
+	echo " --with-dpdk-uadk          Build uadk DPDK module. No path required."
+	echo " --without-dpdk-uadk       Disable uadk DPDK module."
 	echo " --without-uring-zns       Build I/O uring module without ZNS (zoned namespaces) support."
 	echo " --with-openssl[=DIR]      Build OPENSSL with custom path. Otherwise the regular system paths will"
 	echo "                           be searched."
@@ -516,6 +518,12 @@ for i in "$@"; do
 			;;
 		--without-crypto)
 			CONFIG[CRYPTO]=n
+			;;
+		--with-dpdk-uadk)
+			CONFIG[DPDK_UADK]=y
+			;;
+		--without-dpdk-uadk)
+			CONFIG[DPDK_UADK]=n
 			;;
 		--with-vhost)
 			CONFIG[VHOST]=y
@@ -1049,6 +1057,14 @@ if [[ "${CONFIG[UBLK]}" = "y" ]]; then
 		'int main(void) { return 0; }\n' \
 		| "${BUILD_CMD[@]}" -luring - 2> /dev/null; then
 		echo "--with-ublk requires liburing and ublk_drv."
+		echo "Please install then re-run this script."
+		exit 1
+	fi
+fi
+
+if [[ "${CONFIG[DPDK_UADK]}" = "y" ]]; then
+	if ! pkg-config --exists libwd; then
+		echo "--with-dpdk-uadk requires uadk library."
 		echo "Please install then re-run this script."
 		exit 1
 	fi
