compress: Add configure option and build dependencies
Includes the required DPDK dependecies for CompresssDev. Will also
auto-include the SPDK reduce library in 'configure'. Installation
of ISA-L follows same model as ipsec-lib for crypto.

Change-Id: Ic1ea3cbeb9373a7700f6f0c2a3194d65d6a34a41
Signed-off-by: paul luse <paul.e.luse@intel.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -34,6 +34,8 @@ function usage()
 	echo "                           disable features and components."
 	echo ""
 	echo "Valid dependencies are listed below."
+        echo " compress                  Required to build vbdev compression module, will include SPDK reduce library."
+        echo "                           No path required."
 	echo " crypto                    Required to build vbdev crypto module."
 	echo "                           No path required."
 	echo " dpdk                      Optional.  Uses dpdk submodule in spdk tree if not specified."
@@ -48,8 +50,6 @@ function usage()
 	echo "                           No path required."
 	echo " pmdk                      Required to build persistent memory bdev."
 	echo "                           example: /usr/share/pmdk"
-	echo " reduce                    Required to build \"reduce\" (SPDK block compression)."
-	echo "                           No path required."
 	echo " vpp                       Required to build VPP net module."
 	echo "                           example: /vpp_repo/build-root/install-vpp-native/vpp"
 	echo " rbd                       [disabled]"
@@ -192,6 +192,20 @@ for i in "$@"; do
 		--without-dpdk)
 			CONFIG[DPDK_DIR]=
 			;;
+                --with-reduce)
+                        CONFIG[REDUCE]=y
+                        ;;
+                --without-reduce)
+                        CONFIG[REDUCE]=n
+                        ;;
+                --with-compress)
+                        CONFIG[COMPRESS]=y
+			CONFIG[REDUCE]=y
+                        ;;
+                --without-compress)
+                        CONFIG[COMPRESS]=n
+			CONFIG[REDUCE]=n
+			;;
 		--with-crypto)
 			CONFIG[CRYPTO]=y
 			;;
@@ -221,12 +235,6 @@ for i in "$@"; do
 			;;
 		--without-pmdk)
 			CONFIG[PMDK]=n
-			;;
-		--with-reduce)
-			CONFIG[REDUCE]=y
-			;;
-		--without-reduce)
-			CONFIG[REDUCE]=n
 			;;
 		--with-vpp)
 			CONFIG[VPP]=y
@@ -361,24 +369,33 @@ than or equal to 4.14 will see significantly reduced performance.
 	fi
 fi
 
-if [[ "${CONFIG[CRYPTO]}" = "y" ]]; then
-	if [[ $(nasm -v | sed 's/[^0-9]*//g' | awk '{print substr ($0, 0, 5)}') -lt "21202" ]]; then
-		echo Crypto requires NASM version 2.12.02 or newer.  Please install
-		echo or upgrade then re-run this script.
-		exit 1
-        else
-		if [[ "$(find /usr -xdev -name intel-ipsec-mb.h 2>/dev/null)" == "" ]]; then
-			echo "To enable crypto you must first go to the intel-ipsec-mb directory and "
-			echo "run 'make' then 'sudo make install' then re-run this script."
-			exit 1
-		fi
-	fi
+if [[ "${CONFIG[COMPRESS]}" = "y" ]] || [[ "${CONFIG[CRYPTO]}" = "y" ]]; then
+        if [[ $(nasm -v | sed 's/[^0-9]*//g' | awk '{print substr ($0, 0, 5)}') -lt "21202" ]]; then
+                echo Crypto & compression require NASM version 2.12.02 or newer.  Please install
+                echo or upgrade then re-run this script.
+                exit 1
+        fi
 fi
 
-if [[ "${CONFIG[REDUCE]}" = "y" ]]; then
-	if [ ! -f /usr/include/libpmem.h ]; then
-		echo --with-reduce requires libpmem.
-		echo Please install then re-run this script.
+if [[ "${CONFIG[COMPRESS]}" = "y" ]]; then
+	echo NOTE: Compression is currently marked as experimental.  Do not use in production.
+	if [[ "$(find /usr -xdev -name isa-l.h 2>/dev/null)" == "" ]]; then
+		echo "To enable compression you must first go to the isa-l directory and "
+		echo "run 'autogen.sh', 'configure', 'make',  then 'sudo make install' and then "
+		echo "re-run this script."
+		exit 1
+	fi
+        if [ ! -f /usr/include/libpmem.h ]; then
+                echo --with-compress includes the SPDK reduce library which requires libpmem.
+                echo Please install then re-run this script.
+                exit 1
+        fi
+fi
+
+if [[ "${CONFIG[CRYPTO]}" = "y" ]]; then
+	if [[ "$(find /usr -xdev -name intel-ipsec-mb.h 2>/dev/null)" == "" ]]; then
+		echo "To enable crypto you must first go to the intel-ipsec-mb directory and "
+		echo "run 'make' then 'sudo make install' then re-run this script."
 		exit 1
 	fi
 fi
