lib/nvme: add NVMe character device
NVMe character device implementation. This patch adds implementation
of IO producer using CUSE library. It allows to create nvme device
nodes in linux kernel for controller as well as for namespace and
process ioctl requests as usual from linux environment.

Both devices (controller and namespaces) are exposed as character
devices.

Signed-off-by: Jim Harris <james.r.harris@intel.com>
Signed-off-by: Tomasz Kulasek <tomaszx.kulasek@intel.com>
Signed-off-by: Tomasz Zawadzki <tomasz.zawadzki@intel.com>
Change-Id: I0fc9a9a1ef3c9c2b3112d07c2b4b1f8d49665ee1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -94,6 +94,8 @@ function usage()
 	echo "                           be searched."
 	echo " fuse                      Build FUSE components for mounting a blobfs filesystem."
 	echo "                           No path required."
+	echo " nvme-cuse                 Use cuse for NVMe character devices."
+	echo "                           No path required."
 	echo ""
 	echo "Environment variables:"
 	echo ""
@@ -363,6 +365,12 @@ for i in "$@"; do
 		--without-fuse)
 			CONFIG[FUSE]=n
 			;;
+		--with-nvme-cuse)
+			CONFIG[NVME_CUSE]=y
+			;;
+		--without-nvme-cuse)
+			CONFIG[NVME_CUSE]=n
+			;;
 		--)
 			break
 			;;
@@ -606,6 +614,15 @@ if [[ "${CONFIG[VPP]}" = "y" ]]; then
 	if ! echo -e '#include <vnet/session/application_interface.h>\nint main(void) { return 0; }\n' \
 		| ${BUILD_CMD[@]} ${VPP_CFLAGS} -lvppinfra -lsvm -lvlibmemoryclient - 2>/dev/null; then
 		echo --with-vpp requires installed vpp.
+		echo Please install then re-run this script.
+		exit 1
+	fi
+fi
+
+if [[ "${CONFIG[NVME_CUSE]}" = "y" ]]; then
+	if ! echo -e '#define FUSE_USE_VERSION 31\n#include <fuse3/cuse_lowlevel.h>\n#include <fuse3/fuse_lowlevel.h>\n#include <fuse3/fuse_opt.h>\nint main(void) { return 0; }\n' \
+		| ${BUILD_CMD[@]} -lfuse3 -D_FILE_OFFSET_BITS=64 - 2>/dev/null; then
+		echo --with-cuse requires libfuse3.
 		echo Please install then re-run this script.
 		exit 1
 	fi
