configure: validate log backtrace level
Closes #388

Change-Id: Iaac77d878d08962c9a05188eeeb70435e2af0fab
Signed-off-by: Pawel Wodkowski <pawelx.wodkowski@intel.com>
Reviewed-on: https://review.gerrithub.io/421644
Tested-by: SPDK CI Jenkins <sys_sgci@intel.com>
Chandler-Test-Pool: SPDK Automated Test System <sys_sgsw@intel.com>
Reviewed-by: Jim Harris <james.r.harris@intel.com>
Reviewed-by: Ben Walker <benjamin.walker@intel.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -239,6 +239,15 @@ for i in "$@"; do
 	esac
 done
 
+case "$CONFIG_LOG_BACKTRACE" in
+	""|ERROR|WARN|NOTICE|DEBUG)
+		;;
+	*)
+		echo "Invalid '--enable-log-bt=$CONFIG_LOG_BACKTRACE' option. Valid levels are ERROR, WARN, NOTICE or DEBUG"
+		exit 1
+		;;
+esac
+
 if [ -z "$CONFIG_ENV" ]; then
 	if [ -z "$CONFIG_DPDK_DIR" ]; then
 		rootdir=$(readlink -f $(dirname $0))
