bdev/compress: Add configure option and build dependencies
Includes the required DPDK dependencies for SPDK block Reduce aka
Compression.

Change-Id: Ic1ea3cbeb9373a7700f6f0c2a3194d65d6a34a41
Signed-off-by: paul luse <paul.e.luse@intel.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -48,7 +48,7 @@ function usage()
 	echo "                           No path required."
 	echo " pmdk                      Required to build persistent memory bdev."
 	echo "                           example: /usr/share/pmdk"
-	echo " reduce                    Required to build \"reduce\" (SPDK block compression)."
+	echo " reduce                    Required to build vbdev compression module."
 	echo "                           No path required."
 	echo " vpp                       Required to build VPP net module."
 	echo "                           example: /vpp_repo/build-root/install-vpp-native/vpp"
@@ -66,6 +66,8 @@ function usage()
 	echo "                           If argument is directory, interpret it as root of OCF repo"
 	echo "                           If argument is file, interpret it as compiled OCF lib"
 	echo "                           example: /usr/src/ocf/"
+	echo " isal                      Enabled by default on x86 architecture. Can be built without though."
+	echo "                           No path required."
 	echo ""
 	echo "Environment variables:"
 	echo ""
@@ -176,6 +178,12 @@ for i in "$@"; do
 			;;
 		--without-rdma)
 			CONFIG[RDMA]=n
+			;;
+		--with-reduce)
+			CONFIG[REDUCE]=y
+			;;
+		--without-reduce)
+			CONFIG[REDUCE]=n
 			;;
 		--with-shared)
 			CONFIG[SHARED]=y
@@ -304,6 +312,11 @@ if [[ $arch != x86_64* ]]; then
 	CONFIG[ISAL]=n
 fi
 
+if [[ "${CONFIG[ISAL]}" = "n" ]] && [[ "${CONFIG[REDUCE]}" = "y" ]]; then
+		echo "ERROR Conflicting options: --with-reduce is not compatible with --without-isal."
+		exit 1
+fi
+
 if [ -z "${CONFIG[ENV]}" ]; then
 	rootdir=$(readlink -f $(dirname $0))
 	CONFIG[ENV]=$rootdir/lib/env_dpdk
@@ -406,6 +419,7 @@ if [[ "${CONFIG[ISAL]}" = "y" ]] || [[ "${CONFIG[CRYPTO]}" = "y" ]]; then
 		CONFIG[ISAL]=n
 		CONFIG[CRYPTO]=n
 		CONFIG[IPSEC_MB]=n
+		CONFIG[REDUCE]=n
 	else
 		if [[ "${CONFIG[CRYPTO]}" = "y" ]]; then
 			CONFIG[IPSEC_MB]=y
@@ -421,8 +435,9 @@ if [[ "${CONFIG[ISAL]}" = "y" ]]; then
 	fi
 
 	if [[ "${CONFIG[RBD]}" = "y" ]]; then
-		echo "ISAL and RBD cannot co-exist currently so disabling ISAL."
+		echo "ISAL and RBD cannot co-exist currently so disabling ISAL and compression."
 		CONFIG[ISAL]=n
+		CONFIG[REDUCE]=n
 	else
 		cd $rootdir/isa-l
 		ISAL_LOG=/tmp/spdk-isal.log
