build: add configure option to enable/disable VMD
Since VMD is an x86_64-only feature, it's enabled by default on x86_64
(to preserve backwards compatibility) and it's disabled everywhere else.

Change-Id: I73a41cfa6e726c2cb0ba6d44700d83195b7c20e4
Signed-off-by: Konrad Sztyber <ksztyber@nvidia.com>
Reviewed-on: https://review.spdk.io/c/spdk/spdk/+/28946
Reviewed-by: Ben Walker <ben@nvidia.com>
Tested-by: SPDK Automated Test System <spdkbot@gmail.com>
Reviewed-by: Aleksey Marchuk <alexeymar@nvidia.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -141,6 +141,8 @@ function usage() {
 	echo " --without-golang          No path required."
 	echo " --with-aio-fsdev          Build aio FSDEV component."
 	echo " --without-aio-fsdev       No path required."
+	echo " --with-vmd                Enable VMD support."
+	echo " --without-vmd             No path required."
 	echo ""
 	echo "Environment variables:"
 	echo ""
@@ -744,6 +746,12 @@ for i in "$@"; do
 			;;
 		--without-aio-fsdev)
 			CONFIG[AIO_FSDEV]=n
+			;;
+		--with-vmd)
+			CONFIG[VMD]=y
+			;;
+		--without-vmd)
+			CONFIG[VMD]=n
 			;;
 		--)
 			break
@@ -1471,6 +1479,17 @@ if [[ "${CONFIG[CUDA]}" = "y" ]]; then
 		echo "--with-cuda requires cuda build tools!"
 		exit 1
 	fi
+fi
+
+# VMD only works on x86_64, so enable it there by default and disable it everywhere else
+if [[ $arch == x86_64* ]]; then
+	[[ -z "${CONFIG[VMD]}" ]] && CONFIG[VMD]=y
+else
+	if [[ "${CONFIG[VMD]}" == y ]]; then
+		echo "ERROR: VMD is only supported under x86_64"
+		exit 1
+	fi
+	CONFIG[VMD]=n
 fi
 
 # We are now ready to generate final configuration. But first do sanity
