configure: fix up inconsistent indentation
Whitespace modifications only, no functional change.

Change-Id: I984bd4299a7a49d116bee6f723f71e094ecd2209
Signed-off-by: Daniel Verkamp <daniel.verkamp@intel.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -168,11 +168,11 @@ if [ "$CONFIG_ASAN" = "y" -a "$CONFIG_TSAN" = "y" ]; then
 fi
 
 if [[ "$OSTYPE" == "FreeBSD"* ]]; then
-        # FreeBSD doesn't support all configurations
-        if [[ "$CONFIG_COVERAGE" == "y" ]]; then
-                echo "ERROR: CONFIG_COVERAGE not available on FreeBSD"
-                exit 1
-        fi
+	# FreeBSD doesn't support all configurations
+	if [[ "$CONFIG_COVERAGE" == "y" ]]; then
+		echo "ERROR: CONFIG_COVERAGE not available on FreeBSD"
+		exit 1
+	fi
 fi
 
 echo -n "Creating CONFIG.local..."
@@ -229,9 +229,9 @@ python scripts/genconfig.py > config.h
 
 echo "done."
 if [[ "$OSTYPE" == "FreeBSD"* ]]; then
-        echo "Type 'gmake' to build."
+	echo "Type 'gmake' to build."
 else
-        echo "Type 'make' to build."
+	echo "Type 'make' to build."
 fi
 
 exit 0
