bsd: add check for coverage
Error if trying to build with coverage on FreeBSD, this
may be something we try to resolve later but is not a
priority right now so lets just avoid people running into
issues if they try.

Change-Id: Ie90cec38e8fee1e6cfb5ca5d2dbff8a68146569c
Signed-off-by: Paul Luse <paul.e.luse@intel.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -167,6 +167,14 @@ if [ "$CONFIG_ASAN" = "y" -a "$CONFIG_TSAN" = "y" ]; then
 	exit 1
 fi
 
+if [[ "$OSTYPE" == "FreeBSD"* ]]; then
+        # FreeBSD doesn't support all configurations
+        if [[ "$CONFIG_COVERAGE" == "y" ]]; then
+                echo "ERROR: CONFIG_COVERAGE not available on FreeBSD"
+                exit 1
+        fi
+fi
+
 echo -n "Creating CONFIG.local..."
 
 # Write the configuration file
