configure: add --with-fuse option
blobfs_bdev module may contain functions related to
FUSE which will utilize libfuse3.
By default, it is diabled to compile blobfs_bdev module
with FUSE related functions. Running './configure' with
option '--with-fuse' can enable it.

Change-Id: I6552a6c04cc3412c739691630a7a481e0ae6b59c
Signed-off-by: Xiaodong Liu <xiaodong.liu@intel.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -92,6 +92,8 @@ function usage()
 	echo "                           If an argument is provided, it is considered a directory containing"
 	echo "                           liburing.a and io_uring.h. Otherwise the regular system paths will"
 	echo "                           be searched."
+	echo " fuse                      Build FUSE components for mounting a blobfs filesystem."
+	echo "                           No path required."
 	echo ""
 	echo "Environment variables:"
 	echo ""
@@ -354,6 +356,12 @@ for i in "$@"; do
 		--without-uring)
 			CONFIG[URING]=n
 			CONFIG[URING_PATH]=
+			;;
+		--with-fuse)
+			CONFIG[FUSE]=y
+			;;
+		--without-fuse)
+			CONFIG[FUSE]=n
 			;;
 		--)
 			break
@@ -690,6 +698,14 @@ if [[ "${CONFIG[URING]}" = "y" ]]; then
 			echo "${CONFIG[URING_PATH]}: directory not found"
 			exit 1
 		fi
+	fi
+fi
+
+if [[ "${CONFIG[FUSE]}" = "y" ]]; then
+	if [[ ! -d /usr/include/fuse3 ]] && [[ ! -d /usr/local/include/fuse3 ]]; then
+		echo "--with-fuse requires libfuse3."
+		echo "Please install then re-run this script."
+		exit 1
 	fi
 fi
 
