reduce: add configure option
--with-reduce required to build reduce.  This depends on
libpmem being installed.

We still need to work out details in pkgdep.sh and
vm_setup.sh.  Some distributions like Ubuntu still
require configuring extra package repositories to
get libpmem packages.

Signed-off-by: Jim Harris <james.r.harris@intel.com>
Change-Id: I4e056ce1da9a1fecb4458f8f5e7ff5d61c422533

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -48,6 +48,8 @@ function usage()
 	echo "                           No path required."
 	echo " pmdk                      Required to build persistent memory bdev."
 	echo "                           example: /usr/share/pmdk"
+	echo " reduce                    Required to build \"reduce\" (SPDK block compression)."
+	echo "                           No path required."
 	echo " vpp                       Required to build VPP net module."
 	echo "                           example: /vpp_repo/build-root/install-vpp-native/vpp"
 	echo " rbd                       [disabled]"
@@ -220,6 +222,12 @@ for i in "$@"; do
 		--without-pmdk)
 			CONFIG[PMDK]=n
 			;;
+		--with-reduce)
+			CONFIG_REDUCE=y
+			;;
+		--without-reduce)
+			CONFIG_REDUCE=n
+			;;
 		--with-vpp)
 			CONFIG[VPP]=y
 			;;
@@ -367,6 +375,14 @@ if [[ "${CONFIG[CRYPTO]}" = "y" ]]; then
 	fi
 fi
 
+if [[ "${CONFIG[REDUCE]}" = "y" ]]; then
+	if [ ! -f /usr/include/libpmem.h ]; then
+		echo --with-reduce requires libpmem.
+		echo Please install then re-run this script.
+		exit 1
+	fi
+fi
+
 # We are now ready to generate final configuration. But first do sanity
 # check to see if all keys in CONFIG array have its reflection in CONFIG file.
 if [ $(egrep -c "^\s*CONFIG_[[:alnum:]_]+=" CONFIG) -ne ${#CONFIG[@]} ]; then
@@ -377,7 +393,6 @@ if [ $(egrep -c "^\s*CONFIG_[[:alnum:]_]+=" CONFIG) -ne ${#CONFIG[@]} ]; then
 		<(sed -r -e '/^\s*$/d; /^\s*#.*/d; s/(CONFIG_[[:alnum:]_]+)=.*/\1/g' CONFIG | sort) \
 		<(printf "CONFIG_%s\n" ${!CONFIG[@]} | sort)
 	exit 1
-fi
 
 echo -n "Creating mk/config.mk..."
 cp -f CONFIG mk/config.mk
