build: Add support for linking to liburing
liburing is a wrapper around a new Linux kernel interface for
submitting I/O using user space rings. This patch simply
adds the ability to link the nvme perf tool to liburing, but
doesn't implement any of the new functionality yet.

Change-Id: Idb741c87b6d951c013af86e30eac18d3834dd4b7
Signed-off-by: Ben Walker <benjamin.walker@intel.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -73,6 +73,9 @@ function usage()
 	echo "                           example: /usr/src/ocf/"
 	echo " isal                      Enabled by default on x86 architecture. Can be built without though."
 	echo "                           No path required."
+	echo " uring                     Required to support I/O uring on Linux. If no argument, searches"
+	echo "                           the standard installation directory. If an argument is provided, it is"
+	echo "                           considered a directory containing liburing.a and io_uring.h."
 	echo ""
 	echo "Environment variables:"
 	echo ""
@@ -304,6 +307,18 @@ for i in "$@"; do
                 --without-isal)
                         CONFIG[ISAL]=n
                         ;;
+		--with-uring=*)
+			CONFIG[URING]=y
+			CONFIG[URING_PATH]=$(readlink -f ${i#*=})
+			;;
+		--with-uring)
+			CONFIG[URING]=y
+			CONFIG[URING_PATH]=
+			;;
+		--without-uring)
+			CONFIG[URING]=n
+			CONFIG[URING_PATH]=
+			;;
 		--)
 			break
 			;;
@@ -498,6 +513,14 @@ elif [[ "${CONFIG[PGO_USE]}" = "y" ]]; then
 	fi
 fi
 
+if [[ "${CONFIG[URING]}" = "y" ]]; then
+	if [[ -n "${CONFIG[URING_PATH]}" ]]; then
+		if [ ! -d "${CONFIG[URING_PATH]}" ]; then
+			echo "${CONFIG[URING_PATH]}: directory not found"
+			exit 1
+		fi
+	fi
+fi
 
 # We are now ready to generate final configuration. But first do sanity
 # check to see if all keys in CONFIG array have its reflection in CONFIG file.
