[RFC]vhost/fs: add virtio-fs support
In order to compile vhost-fs, use configure with
 --with-vhost-fs like this:
./configure --with-vhost-fs  --with-internal-vhost-lib

A vhost-user-fs device can be created by:
./scripts/rpc.py construct_vhost_fs_controller fuse0 AIO1
Or add a VhostFS section into conf file:
[VhostFS0]
  Name vhost.fs0
  Dev  AIO1

Corresponding Qemu and Kernel are:
Kernel: https://gitlab.com/virtio-fs/linux/tree/virtio-fs-dev
Qemu:	https://gitlab.com/virtio-fs/qemu/tree/virtio-fs-dev

Notes:
It is now in stage of supporting rootfs.
Directory ability is limited and volatile.
Attributes and symlinks are required.

Change-Id: I8c258445b369693baefd5914da1f55546f14b7d4
Signed-off-by: Liu Xiaodong <xiaodong.liu@intel.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -57,7 +57,8 @@ function usage()
 	echo " vhost                     Build vhost target. Enabled by default."
 	echo "                           No path required."
 	echo " internal-vhost-lib        Use the internal copy of rte_vhost. By default, the upstream"
-	echo "                           rte_vhost from DPDK will be used."
+        echo "                           rte_vhost from DPDK will be used."
+	echo " vhost-fs                  Required to build vhost-fs target."
 	echo "                           No path required."
 	echo " virtio                    Build vhost initiator and virtio-pci bdev modules."
 	echo "                           No path required."
@@ -270,6 +271,12 @@ for i in "$@"; do
 		--without-internal-vhost-lib)
 			CONFIG[VHOST_INTERNAL_LIB]=n
 			;;
+		--with-vhost-fs)
+			CONFIG[VHOST_FS]=y
+			;;
+		--without-vhost-fs)
+			CONFIG[VHOST_FS]=n
+			;;
 		--with-virtio)
 			CONFIG[VIRTIO]=y
 			;;
@@ -472,6 +479,13 @@ if [ "${CONFIG[FIO_PLUGIN]}" = "y" ]; then
 	fi
 else
 	CONFIG[FIO_SOURCE_DIR]=
+fi
+
+if [ "${CONFIG[VHOST_FS]}" = "y" ]; then
+	if [ "${CONFIG[VHOST]}" = "n" ]; then
+		echo "Vhost-fs is only supported when vhost is enabled."
+		exit 1
+	fi
 fi
 
 if [ "${CONFIG[VTUNE]}" = "y" ]; then
