bdev/compress: Add configure option and build dependencies
Includes the required DPDK dependencies for SPDK block Reduce aka
Compression.

As ISA-L was added here initially for compression, it
has been included as a requirement in this patch for all x86 machines
so that it can be used by various utils across SPDK however it can
be disabled manually by using --without-isal. Note that this patch
supprots ISA-L for DPDK (reduce) only which requires an installation
of ISA-L.  Future work can modify the instalation requirement
accordingly (ie use libraries instead).

Configure also updated to check the various combinations of new options
that don't work together and fail when its not clear which option makes
sense, in the cases of missing deps we now just disable the option and
print a message..

Updated pkg_dep compression and crypto dependency check/install
to provide more user output.

Change-Id: Ic1ea3cbeb9373a7700f6f0c2a3194d65d6a34a41
Signed-off-by: paul luse <paul.e.luse@intel.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -42,24 +42,26 @@ function usage()
 	echo "                           example: /usr/src/fio"
 	echo " igb-uio-driver            Required on some systems to use qat devices"
 	echo "                           No path required"
-	echo " vhost                     Required to build vhost target."
-	echo "                           No path required."
-	echo " virtio                    Required to build vhost initiator (Virtio) bdev module."
+	echo " isal			 Storage acceleration library, configured --with by default."
+	echo "                           No path required"
+	echo " iscsi-initiator           [disabled]"
 	echo "                           No path required."
 	echo " pmdk                      Required to build persistent memory bdev."
 	echo "                           example: /usr/share/pmdk"
-	echo " reduce                    Required to build \"reduce\" (SPDK block compression)."
-	echo "                           No path required."
-	echo " vpp                       Required to build VPP net module."
-	echo "                           example: /vpp_repo/build-root/install-vpp-native/vpp"
 	echo " rbd                       [disabled]"
+	echo "                           No path required."
+	echo " reduce                    Required to build vbdev compression module."
 	echo "                           No path required."
 	echo " rdma                      [disabled]"
 	echo "                           No path required."
 	echo " shared                    Required to build spdk shared libraries."
 	echo "                           No path required."
-	echo " iscsi-initiator           [disabled]"
+	echo " vhost                     Required to build vhost target."
 	echo "                           No path required."
+	echo " virtio                    Required to build vhost initiator (Virtio) bdev module."
+	echo "                           No path required."
+	echo " vpp                       Required to build VPP net module."
+	echo "                           example: /vpp_repo/build-root/install-vpp-native/vpp"
 	echo " vtune                     Required to profile I/O under Intel VTune Amplifier XE."
 	echo "                           example: /opt/intel/vtune_amplifier_xe_version"
 	echo ""
@@ -192,6 +194,12 @@ for i in "$@"; do
 		--without-dpdk)
 			CONFIG[DPDK_DIR]=
 			;;
+                --with-reduce)
+                        CONFIG[REDUCE]=y
+                        ;;
+                --without-reduce)
+                        CONFIG[REDUCE]=n
+                        ;;
 		--with-crypto)
 			CONFIG[CRYPTO]=y
 			;;
@@ -221,12 +229,6 @@ for i in "$@"; do
 			;;
 		--without-pmdk)
 			CONFIG[PMDK]=n
-			;;
-		--with-reduce)
-			CONFIG[REDUCE]=y
-			;;
-		--without-reduce)
-			CONFIG[REDUCE]=n
 			;;
 		--with-vpp)
 			CONFIG[VPP]=y
@@ -269,6 +271,12 @@ for i in "$@"; do
 		--without-ftl)
 			CONFIG[FTL]=n
 			;;
+                --with-isal)
+                        CONFIG[ISAL]=y
+                        ;;
+                --without-isal)
+                        CONFIG[ISAL]=n
+                        ;;
 		--)
 			break
 			;;
@@ -278,6 +286,13 @@ for i in "$@"; do
 			exit 1
 	esac
 done
+
+# Detect architecture and force no isal if non x86 archt
+arch=$(uname -i)
+if [[ $arch != x86_64* ]]; then
+	echo "Notice: ISAL auto-disabled due to CPU incompatiblity."
+	CONFIG[ISAL]=n
+fi
 
 if [ -z "${CONFIG[ENV]}" ]; then
 	rootdir=$(readlink -f $(dirname $0))
@@ -373,25 +388,49 @@ than or equal to 4.14 will see significantly reduced performance.
 	fi
 fi
 
-if [[ "${CONFIG[CRYPTO]}" = "y" ]]; then
-	if [[ $(nasm -v | sed 's/[^0-9]*//g' | awk '{print substr ($0, 0, 5)}') -lt "21202" ]]; then
-		echo Crypto requires NASM version 2.12.02 or newer.  Please install
-		echo or upgrade then re-run this script.
+if [[ "${CONFIG[ISAL]}" = "n" ]] && [[ "${CONFIG[REDUCE]}" = "y" ]]; then
+		echo "ERROR Conflicting options: --with-reduce is not compatible with --without-isal."
 		exit 1
-        else
-		if [[ "$(find /usr -xdev -name intel-ipsec-mb.h 2>/dev/null)" == "" ]]; then
-			echo "To enable crypto you must first go to the intel-ipsec-mb directory and "
-			echo "run 'make' then 'sudo make install' then re-run this script."
-			exit 1
-		fi
-	fi
+fi
+
+if [[ "${CONFIG[PMDK]}" = "n" ]] && [[ "${CONFIG[REDUCE]}" = "y" ]]; then
+		echo "ERROR Conflicting options: --with-reduce requires --with-pmdk."
+		exit 1
+fi
+
+if [[ "${CONFIG[ISAL]}" = "y" ]] || [[ "${CONFIG[CRYPTO]}" = "y" ]]; then
+        if [[ $(nasm -v | sed 's/[^0-9]*//g' | awk '{print substr ($0, 0, 5)}') -lt "21202" ]]; then
+		echo "Notice: ISAL & Crypto auto-disabled due to nasm dependency."
+		echo "Crypto & ISAL require NASM version 2.12.02 or newer.  Please install"
+		echo "or upgrade then re-run this script."
+		CONFIG[ISAL]=n
+		CONFIG[CRYPTO]=n
+        fi
 fi
 
 if [[ "${CONFIG[REDUCE]}" = "y" ]]; then
-	if [ ! -f /usr/include/libpmem.h ]; then
-		echo --with-reduce requires libpmem.
-		echo Please install then re-run this script.
-		exit 1
+	echo NOTE: Compression is currently marked as experimental.  Do not use in production.
+        if [ ! -f /usr/include/libpmem.h ]; then
+		echo "Notice: Compression auto-disabled due to pmdk dependency."
+		echo "To enable compression you must first install pmdk"
+		echo "and then re-run this script."
+		CONFIG[REDUCE]=n
+        fi
+fi
+
+if [[ "${CONFIG[CRYPTO]}" = "y" ]]; then
+        if [[ "$(find /usr -xdev -name isa-l.h 2>/dev/null)" == "" ]]; then
+		echo "Notice: Crypto auto-disabled due to isal dependency."
+		echo "To enable crypto you must first go to the isa-l directory and "
+		echo "run 'autogen.sh', 'configure', 'make',  then 'sudo make install' and then "
+		echo "re-run this script."
+		CONFIG[CRYPTO]=n
+	fi
+	if [[ "$(find /usr -xdev -name intel-ipsec-mb.h 2>/dev/null)" == "" ]]; then
+		echo "Notice: Crypto auto-disabled due to ipsec dependency."
+		echo "To enable crypto you must first go to the intel-ipsec-mb directory and "
+		echo "run 'make' then 'sudo make install' then re-run this script."
+		CONFIG[CRYPTO]=n
 	fi
 fi
 
