Add support for VTune
Change-Id: Ica7f76a5354b27e6e5fd7114de1fdba46434b073
Signed-off-by: Roman Sudarikov <roman.sudarikov@intel.com>
Reviewed-on: https://review.gerrithub.io/362994
Reviewed-by: Daniel Verkamp <daniel.verkamp@intel.com>
Tested-by: SPDK Automated Test System <sys_sgsw@intel.com>
Reviewed-by: Ben Walker <benjamin.walker@intel.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -35,6 +35,8 @@ function usage()
 	echo "                           No path required."
 	echo " rdma                      [disabled]"
 	echo "                           No path required."
+	echo " vtune                     Required to profile I/O under Intel VTune Amplifier XE."
+	echo "                           example: /opt/intel/vtune_amplifier_xe_version"
 	echo ""
 }
 
@@ -115,6 +117,14 @@ for i in "$@"; do
 			FIO_SOURCE_DIR=
 			CONFIG_FIO_PLUGIN=n
 			;;
+		--with-vtune=*)
+			VTUNE_SOURCE_DIR="${i#*=}"
+			CONFIG_VTUNE=y
+			;;
+		--without-vtune)
+			VTUNE_SOURCE_DIR=
+			CONFIG_VTUNE=n
+			;;
 		--)
 			break
 			;;
@@ -141,6 +151,13 @@ fi
 if [ "$CONFIG_FIO_PLUGIN" = "y" ]; then
 	if [ -z "$FIO_SOURCE_DIR" ]; then
 		echo "When fio is enabled, you must specify the fio directory using --with-fio=path"
+		exit 1
+	fi
+fi
+
+if [ "$CONFIG_VTUNE" = "y" ]; then
+	if [ -z "$VTUNE_SOURCE_DIR" ]; then
+		echo "When VTune is enabled, you must specify the VTune directory using --with-vtune=path"
 		exit 1
 	fi
 fi
@@ -192,6 +209,12 @@ if [ -n "$CONFIG_RDMA" ]; then
 fi
 if [ -n "$CONFIG_RBD" ]; then
 	echo "CONFIG_RBD?=$CONFIG_RBD" >> CONFIG.local
+fi
+if [ -n "$CONFIG_VTUNE" ]; then
+	echo "CONFIG_VTUNE?=$CONFIG_VTUNE" >> CONFIG.local
+fi
+if [ -n "$VTUNE_SOURCE_DIR" ]; then
+	echo "VTUNE_SOURCE_DIR?=$VTUNE_SOURCE_DIR" >> CONFIG.local
 fi
 
 python scripts/genconfig.py > config.h
