configure: don't allow --with-fio and --disable-examples
These options are mutually exclusive - fio plugins are
part of the examples directory hierarchy, so it is
confusing to express --with-fio and not see the fio
plugins get built.

Signed-off-by: Jim Harris <james.r.harris@intel.com>
Change-Id: I1e30db1d99d317f8c22318e7ae2d3dd461f18a42
Reviewed-on: https://review.spdk.io/gerrit/c/spdk/spdk/+/13055
Community-CI: Broadcom CI <spdk-ci.pdl@broadcom.com>
Community-CI: Mellanox Build Bot
Reviewed-by: Paul Luse <paul.e.luse@intel.com>
Reviewed-by: Changpeng Liu <changpeng.liu@intel.com>
Reviewed-by: Thanos Makatos <thanos.makatos@nutanix.com>
Reviewed-by: Ben Walker <benjamin.walker@intel.com>
Tested-by: SPDK CI Jenkins <sys_sgci@intel.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -774,6 +774,11 @@ if [[ "${CONFIG[ASAN]}" = "y" && "${CONFIG[TSAN]}" = "y" ]]; then
 	exit 1
 fi
 
+if [[ "${CONFIG[FIO_PLUGIN]}" = "y" && "${CONFIG[EXAMPLES]}" = "n" ]]; then
+	echo "ERROR: --with-fio and --disable-examples are mutually exclusive."
+	exit 1
+fi
+
 if [[ $sys_name == "FreeBSD" ]]; then
 	# FreeBSD doesn't support all configurations
 	if [[ "${CONFIG[COVERAGE]}" == "y" ]]; then
