pkgdep/git: Use $CC to determine version of the compiler
Don't assume gcc will be in use during build since most of the sources
we support use tooling which extensively uses environment for detecting
compilers to use.

Change-Id: I78edd7d13f3c61215bf1352b91662eda52553593
Signed-off-by: Michal Berger <michallinuxstuff@gmail.com>
Reviewed-on: https://review.spdk.io/c/spdk/spdk/+/25584
Tested-by: SPDK Automated Test System <spdkbot@gmail.com>
Reviewed-by: Tomasz Zawadzki <tomasz@tzawadzki.com>
Reviewed-by: Jim Harris <jim.harris@nvidia.com>

diff --git a/test/common/config/pkgdep/git b/test/common/config/pkgdep/git
--- a/test/common/config/pkgdep/git
+++ b/test/common/config/pkgdep/git
@@ -128,7 +128,7 @@ function _install_qemu() {
 	declare -a extra_cflags=()
 
 	opt_params+=("--disable-docs")
-	if ((gcc_version >= 9)); then
+	if [[ $CC == *gcc* ]] && ((cc_version >= 9)); then
 		opt_params+=("--disable-glusterfs")
 	fi
 
@@ -625,13 +625,14 @@ export GIT_REPO_DOXYGEN
 export GIT_REPO_LIBBPF
 
 GIT_REPOS=${GIT_REPOS:-$HOME}
+CC=${CC:-gcc}
 
-if ! gcc_version=$(gcc -dumpversion 2> /dev/null); then
-	echo "gcc version could not be determined, aborting" >&2
+if ! cc_version=$($CC -dumpversion 2> /dev/null); then
+	echo "'$CC' version could not be determined, aborting" >&2
 	return 1
 fi
 
-gcc_version=${gcc_version%%.*}
+cc_version=${cc_version%%.*}
 if [[ -e /proc/sys/kernel/osrelease ]]; then
 	kernel_ver=$(< /proc/sys/kernel/osrelease)
 fi
