pkgdep/git: Fail early and verbosely when gcc is missing
Change-Id: I2e8add64fe69a6807c007f02d1265403ef664cda
Signed-off-by: Michal Berger <michallinuxstuff@gmail.com>
Reviewed-on: https://review.spdk.io/c/spdk/spdk/+/25583
Tested-by: SPDK Automated Test System <spdkbot@gmail.com>
Reviewed-by: Jim Harris <jim.harris@nvidia.com>
Reviewed-by: Tomasz Zawadzki <tomasz@tzawadzki.com>

diff --git a/test/common/config/pkgdep/git b/test/common/config/pkgdep/git
--- a/test/common/config/pkgdep/git
+++ b/test/common/config/pkgdep/git
@@ -626,7 +626,12 @@ export GIT_REPO_LIBBPF
 
 GIT_REPOS=${GIT_REPOS:-$HOME}
 
-gcc_version=$(gcc -dumpversion) gcc_version=${gcc_version%%.*}
+if ! gcc_version=$(gcc -dumpversion 2> /dev/null); then
+	echo "gcc version could not be determined, aborting" >&2
+	return 1
+fi
+
+gcc_version=${gcc_version%%.*}
 if [[ -e /proc/sys/kernel/osrelease ]]; then
 	kernel_ver=$(< /proc/sys/kernel/osrelease)
 fi
